n = input("digite algo:")
print("o tipo prrimitivo desse valor é", type(n))
print("so tem espaços?", n.isspace())
print("é um numero?", n.isnumeric())
print("é alfabeitico?", n.isalpha())
print("é alfanumerico?", n.isalnum())
print("está em maisculas?", n.isupper())
print("está em minusculas?", n.islower())
print("está capitalizado( a primeira letra é maiuscula)?", n.istitle())
